### ISSUE TITLE
rebirths are useless in trials so lets just yeet them off

### ISSUE THREAD

**Issue by TrueDiegoWasAlsoTaken** [YhvrWasTaken/tree-game#5]
I don't feel like the rebirth button should be in the tree inside a trial as there is no use for it inside one. 

I suggest the rebirth button gets replaced with the "Complete the Trial" button inside trials, as well as being able to use the "R" hotkey for it.

**Comment by IAmYhvr** [comment]
Fixed (not pushed yet).
